## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Create highly available three-tier web application in Oracle Cloud Infrastructure"
    stackDescription: "Deploy a highly available three-tier web application in Oracle Cloud Infrastructure"
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid

    - title: Required Configuration
      visible: true  
      variables:
      - compartment_ocid
      - region
      - availability_domain
      - ATP_password
      - ATP_data_guard_enabled 

    - title: Optional Configuration
      visible: true
      variables:
      - instance_os
      - instance_shape
      - linux_os_version 
      - ATP_database_cpu_core_count
      - ATP_database_data_storage_size_in_tbs
      - ATP_database_db_name
      - ATP_database_db_version
      - ATP_database_defined_tags_value
      - ATP_database_display_name
      - ATP_database_freeform_tags
      - ATP_database_license_model
      - ATP_tde_wallet_zip_file
      - ATP_private_endpoint_label

    variables:
      
      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Region where you want to deploy the resources defined by this stack."

      availability_domain:
        type: oci:identity:availabilitydomain:name
        dependsOn:
          compartmentId: ${compartment_ocid}
        required: true
        visibile: true
        title: "Availability Domain to be chosen."
        description: "Availability Domain to be chosen."
        default: "3"

      ATP_password:
        type: password
        required: true
        visibile: true
        title: "ATP Database Password for ADMIN user."
        description: "ATP Database Password for ADMIN user."

      ATP_data_guard_enabled:
        type: boolean
        required: true
        visibile: true
        default: false
        description: "ATP Database DataGuard Enabled"        

      # Optional Configuration      
      instance_shape:
        type: oci:core:instanceshape:name
        required: true
        title: "Instance Shape"
        description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
        default: "VM.Standard2.1"
        dependsOn:
          compartmentId: ${compartment_ocid}
      
      instance_os:
        type: oci:core:instanceos:name
        required: true
        title: "Instance OS"
        description: "An Oper"ating System that determines the operating system for the instance."
        default: "Oracle Linux"
        dependsOn:
          compartmentId: ${compartment_ocid}
      
      linux_os_version:
        type: oci:core:linuxosversion:name
        required: true
        title: "Instance OS version"
        description: "An Operating System version that determines the operating system version for the instance."
        default: "7.8"
        dependsOn:
          compartmentId: ${compartment_ocid}
      
      ATP_database_cpu_core_count:
        type: number
        required: false
        default: 1
        description: "ATP Database CPU Core Count"

      ATP_database_data_storage_size_in_tbs:
        type: number
        required: false
        default: 1
        description: "ATP Database Data Storage Size in terabytes"

      ATP_database_db_name:
        type: string
        required: false
        default: "atpdb1"
        description: "ATP Database DBNAME"

      ATP_database_db_version:
        type: string
        required: false
        default: "19c"
        description: "ATP Database Version"

      ATP_database_display_name:
        type: string
        required: false
        default: "ATPDB"
        description: "ATP Database Display Name"

      ATP_database_license_model:
        type: string
        required: false
        default: "LICENSE_INCLUDED"
        description: "ATP Database License Model"

      ATP_tde_wallet_zip_file:
        type: string
        required: false
        default: "tde_wallet_ATPdb1.zip"
        description: "ATP Database TDE Wallet ZIP File"
      
      ATP_private_endpoint_label:
        type: string
        required: false
        default: "ATPPrivateEndpoint"
        description: "ATP Database Private Endpoint Label"

      ATP_database_freeform_tags:
        type: string
        required: false
        description: "ATP Database Freeform Tags"

      ATP_database_defined_tags_value:
        type: string
        required: false
        description: "ATP Database Defined Tags"

    outputs:
      loadbalancer_public_pl:
      title: "LoadBalancer Public IP"
      displayText: "LoadBalancer Public IP"
      type: copyableString
      visible: true
  
     generated_ssh_private_key:
       title: "Generated SSH Private Key"
       displayText: "Generated SSH Private Key"
       type: copyableString
       visible: true
    