
    # Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    # Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

    title: "Highly available three-tier web application"
    stackDescription: Deploy a highly available sample flask web application
    schemaVersion: 1.1.0
    version: "20200601"
    locale: "en"

    variableGroups:
      - title: General Configuration
        visible: false
        variables:
        - compartment_ocid
        - tenancy_ocid
        - region
        - availability_domain
        - instance_os
        - instance_shape
        - linux_os_version

      - title: Required Configuration
        visible: true  
        variables:
        - ATP_password

      - title: Optional Configuration
        visible: true
        variables:
        - ssh_public_key
        - ssh_private_key

    variables:
      
      compartment_ocid:
        type: oci:identity:compartment:id
        # type: string
        required: true
        title: Compartment
        description: Compartment where you want to create the solution resources

      availability_domain:
        type: oci:identity:availabilitydomain:name
        dependsOn:
          compartmentId: ${compartment_ocid}
        required: true
        title: Availability Domain
        description: Availability Domain
        default: "3"
      
      region:
        type: enum
        required: true
        title: Region
        description: Region where you want to deploy the resources defined by this stack
        default: "us-ashburn-1"
        enum:
          - "us-phoenix-1"
          - "us-ashburn-1"
          - "eu-frankfurt-1"
          - "uk-london-1"
          - "us-seattle-1"
          - "r1"
      
      instance_shape:
        type: oci:core:instanceshape:name
        required: true
        title: Instance Shape
        description: A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance.
        default: "VM.Standard2.1"
        dependsOn:
          compartmentId: ${compartment_ocid}
      
      instance_os:
        type: oci:core:instanceos:name
        required: true
        title: Instance OS
        description: An Operating System that determines the operating system for the instance.
        default: "Oracle Linux"
        dependsOn:
          compartmentId: ${compartment_ocid}
      
      linux_os_version:
        type: oci:core:linuxosversion:name
        required: true
        title: Instance OS version
        description: An Operating System version that determines the operating system version for the instance.
        default: "7.8"
        dependsOn:
          compartmentId: ${compartment_ocid}
      
      ATP_password:
        type: string
        required: true
        title: ATP database passowrd
        description: password for of the ATP Database
        default: "BEstrO0ng_#12"
        minLength: 1
        maxLength: 14

      ssh_public_key:
        type: text
        required: false
        title: SSH Public Key
        description: A public key is used to authenticate to remote compute instances. 

      ssh_private_key:
        type: text
        required: false
        title: SSH Private Key
        description: A private key is used to authenticate to remote compute instances. 
    